# Generated by Django 5.2.14 on 2026-05-09 22:57

import core.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True, verbose_name="nome")),
                (
                    "cor",
                    models.CharField(
                        blank=True, help_text="Hex #RRGGBB", max_length=7, verbose_name="cor"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                ("ativo", models.BooleanField(default=True, verbose_name="ativa")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criada em")),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ["nome"],
                "indexes": [models.Index(fields=["ativo"], name="pessoas_tag_ativo_f59b0a_idx")],
            },
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=9,
                        validators=[core.utils.validate_cep],
                        verbose_name="CEP",
                    ),
                ),
                (
                    "logradouro",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="logradouro"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, default="", max_length=20, verbose_name="número"),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="complemento"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "slug_publico",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Slug curto para URLs públicas. Gerado automaticamente no pre_save.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                ("sobrenome", models.CharField(max_length=150, verbose_name="sobrenome")),
                (
                    "nome_social",
                    models.CharField(blank=True, max_length=200, verbose_name="nome social"),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=14,
                        validators=[core.utils.validate_cpf],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(blank=True, null=True, verbose_name="data de nascimento"),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mulher", "Mulher"),
                            ("homem", "Homem"),
                            ("nao_binario", "Não-binário"),
                            ("outro", "Outro"),
                            ("prefere_nao_dizer", "Prefere não dizer"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="gênero",
                    ),
                ),
                ("bairro", models.CharField(max_length=100, verbose_name="bairro")),
                ("cidade", models.CharField(max_length=100, verbose_name="cidade")),
                (
                    "estado",
                    models.CharField(
                        default="ES",
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z]{2}$", "Use a sigla de 2 letras (ex: ES)."
                            )
                        ],
                        verbose_name="estado (UF)",
                    ),
                ),
                ("observacoes", models.TextField(blank=True, verbose_name="observações")),
                (
                    "origem_cadastro",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("inbox", "Inbox"),
                            ("importacao", "Importação"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="origem do cadastro",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                ("anonimizado", models.BooleanField(default=False, verbose_name="anonimizado")),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pessoas_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="pessoas", to="pessoas.tag"),
                ),
            ],
            options={
                "verbose_name": "pessoa",
                "verbose_name_plural": "pessoas",
                "ordering": ["nome", "sobrenome"],
                "permissions": [
                    ("pode_desativar_pessoa", "Pode desativar pessoa (soft delete)"),
                    ("pode_reativar_pessoa", "Pode reativar pessoa desativada"),
                    ("pode_anonimizar_pessoa", "Pode anonimizar pessoa (LGPD)"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Entidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=9,
                        validators=[core.utils.validate_cep],
                        verbose_name="CEP",
                    ),
                ),
                (
                    "logradouro",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="logradouro"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, default="", max_length=20, verbose_name="número"),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="complemento"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="bairro"),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="cidade"),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z]{2}$", "Use a sigla de 2 letras (ex: ES)."
                            )
                        ],
                        verbose_name="estado (UF)",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "slug_publico",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Slug curto para URLs públicas. Gerado automaticamente no pre_save.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="nome")),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="nome fantasia"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("associacao_de_moradores", "Associação de moradores"),
                            ("sindicato", "Sindicato"),
                            ("partido", "Partido"),
                            ("escola", "Escola"),
                            ("conselho", "Conselho"),
                            ("igreja", "Igreja"),
                            ("ong", "ONG"),
                            ("empresa", "Empresa"),
                            ("orgao_publico", "Órgão público"),
                            ("coletivo", "Coletivo"),
                            ("familia", "Família"),
                            ("grupo_informal", "Grupo informal"),
                            ("condominio", "Condomínio"),
                            ("outros", "Outros"),
                        ],
                        max_length=30,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=18,
                        validators=[core.utils.validate_cnpj_tamanho],
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="telefone"
                    ),
                ),
                (
                    "site",
                    models.URLField(blank=True, default="", max_length=255, verbose_name="site"),
                ),
                ("observacoes", models.TextField(blank=True, verbose_name="observações")),
                ("ativo", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entidades_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="entidades", to="pessoas.tag"),
                ),
            ],
            options={
                "verbose_name": "entidade",
                "verbose_name_plural": "entidades",
                "ordering": ["nome"],
                "permissions": [
                    ("pode_desativar_entidade", "Pode desativar entidade (soft delete)"),
                    ("pode_reativar_entidade", "Pode reativar entidade desativada"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Telefone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("numero", models.CharField(max_length=20, verbose_name="número")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("celular", "Celular"), ("fixo", "Fixo")],
                        default="celular",
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                ("eh_whatsapp", models.BooleanField(default=False, verbose_name="é WhatsApp")),
                (
                    "rotulo",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Opcional. Ex: "trabalho", "recado da mãe".',
                        max_length=50,
                        verbose_name="rótulo",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telefones",
                        to="pessoas.pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "telefone",
                "verbose_name_plural": "telefones",
                "ordering": ["-eh_whatsapp", "criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Vinculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("papel", models.CharField(max_length=100, verbose_name="papel")),
                ("data_inicio", models.DateField(blank=True, null=True, verbose_name="início")),
                ("data_fim", models.DateField(blank=True, null=True, verbose_name="fim")),
                ("observacao", models.TextField(blank=True, verbose_name="observação")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos",
                        to="pessoas.entidade",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos",
                        to="pessoas.pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo",
                "verbose_name_plural": "vínculos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="pessoa",
            name="entidades",
            field=models.ManyToManyField(
                blank=True, related_name="pessoas", through="pessoas.Vinculo", to="pessoas.entidade"
            ),
        ),
        migrations.CreateModel(
            name="EmailPessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("endereco", models.EmailField(max_length=254, verbose_name="endereço")),
                (
                    "rotulo",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Opcional. Ex: "trabalho", "pessoal".',
                        max_length=50,
                        verbose_name="rótulo",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="pessoas.pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "e-mail",
                "verbose_name_plural": "e-mails",
                "ordering": ["criado_em"],
                "indexes": [
                    models.Index(fields=["endereco"], name="pessoas_ema_enderec_e89ce0_idx"),
                    models.Index(fields=["pessoa"], name="pessoas_ema_pessoa__0a8579_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RedeSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "plataforma",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                            ("x_twitter", "X (Twitter)"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="plataforma",
                    ),
                ),
                (
                    "valor",
                    models.CharField(
                        help_text="@handle ou URL do perfil.",
                        max_length=255,
                        verbose_name="usuário ou URL",
                    ),
                ),
                (
                    "rotulo",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Opcional. Especialmente útil quando plataforma="Outro" para indicar qual rede.',
                        max_length=50,
                        verbose_name="rótulo",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redes_sociais",
                        to="pessoas.pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "rede social",
                "verbose_name_plural": "redes sociais",
                "ordering": ["plataforma", "criado_em"],
                "indexes": [
                    models.Index(fields=["plataforma"], name="pessoas_red_platafo_ed0f9e_idx"),
                    models.Index(fields=["pessoa"], name="pessoas_red_pessoa__6e1278_idx"),
                    models.Index(fields=["valor"], name="pessoas_red_valor_6f6d66_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="entidade",
            index=models.Index(fields=["nome"], name="pessoas_ent_nome_d58238_idx"),
        ),
        migrations.AddIndex(
            model_name="entidade",
            index=models.Index(fields=["tipo"], name="pessoas_ent_tipo_66dad0_idx"),
        ),
        migrations.AddIndex(
            model_name="entidade",
            index=models.Index(fields=["ativo"], name="pessoas_ent_ativo_fd5db6_idx"),
        ),
        migrations.AddConstraint(
            model_name="entidade",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cnpj", ""), _negated=True),
                fields=("cnpj",),
                name="entidade_cnpj_unico_quando_preenchido",
            ),
        ),
        migrations.AddIndex(
            model_name="telefone",
            index=models.Index(fields=["numero"], name="pessoas_tel_numero_594ca7_idx"),
        ),
        migrations.AddIndex(
            model_name="telefone",
            index=models.Index(fields=["pessoa"], name="pessoas_tel_pessoa__ab93bc_idx"),
        ),
        migrations.AddIndex(
            model_name="vinculo",
            index=models.Index(fields=["pessoa"], name="pessoas_vin_pessoa__5d4d2a_idx"),
        ),
        migrations.AddIndex(
            model_name="vinculo",
            index=models.Index(fields=["entidade"], name="pessoas_vin_entidad_57f197_idx"),
        ),
        migrations.AddIndex(
            model_name="pessoa",
            index=models.Index(fields=["nome", "sobrenome"], name="pessoas_pes_nome_4e071a_idx"),
        ),
        migrations.AddIndex(
            model_name="pessoa",
            index=models.Index(fields=["bairro"], name="pessoas_pes_bairro_966ee6_idx"),
        ),
        migrations.AddIndex(
            model_name="pessoa",
            index=models.Index(fields=["ativo"], name="pessoas_pes_ativo_a717a9_idx"),
        ),
        migrations.AddConstraint(
            model_name="pessoa",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cpf", ""), _negated=True),
                fields=("cpf",),
                name="pessoa_cpf_unico_quando_preenchido",
            ),
        ),
    ]
