# Generated by Django 5.2.14 on 2026-05-08 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True, verbose_name="nome")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("tema", "Tema"),
                            ("perfil", "Perfil"),
                            ("territorio", "Território"),
                            ("livre", "Livre"),
                        ],
                        default="livre",
                        max_length=15,
                        verbose_name="categoria",
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        blank=True, help_text="Hex #RRGGBB", max_length=7, verbose_name="cor"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                ("ativo", models.BooleanField(default=True, verbose_name="ativa")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criada em")),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ["categoria", "nome"],
                "indexes": [
                    models.Index(fields=["categoria"], name="pessoas_tag_categor_41634f_idx"),
                    models.Index(fields=["ativo"], name="pessoas_tag_ativo_f59b0a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                ("sobrenome", models.CharField(max_length=150, verbose_name="sobrenome")),
                (
                    "nome_social",
                    models.CharField(blank=True, max_length=200, verbose_name="nome social"),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, default="", max_length=14, verbose_name="CPF"),
                ),
                (
                    "data_nascimento",
                    models.DateField(blank=True, null=True, verbose_name="data de nascimento"),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mulher", "Mulher"),
                            ("homem", "Homem"),
                            ("nao_binario", "Não-binário"),
                            ("outro", "Outro"),
                            ("prefere_nao_dizer", "Prefere não dizer"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="gênero",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="telefone"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sem o @",
                        max_length=50,
                        verbose_name="Instagram",
                    ),
                ),
                ("cep", models.CharField(blank=True, default="", max_length=9, verbose_name="CEP")),
                (
                    "logradouro",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="logradouro"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, default="", max_length=20, verbose_name="número"),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="complemento"
                    ),
                ),
                ("bairro", models.CharField(max_length=100, verbose_name="bairro")),
                ("cidade", models.CharField(max_length=100, verbose_name="cidade")),
                (
                    "estado",
                    models.CharField(default="ES", max_length=2, verbose_name="estado (UF)"),
                ),
                ("nao_telefonar", models.BooleanField(default=False, verbose_name="não telefonar")),
                (
                    "nao_enviar_email",
                    models.BooleanField(default=False, verbose_name="não enviar e-mail em massa"),
                ),
                (
                    "nao_enviar_sms",
                    models.BooleanField(
                        default=False, verbose_name="não enviar SMS/WhatsApp em massa"
                    ),
                ),
                (
                    "nao_compartilhar_dados",
                    models.BooleanField(
                        default=False, verbose_name="não compartilhar dados com terceiros"
                    ),
                ),
                ("observacoes", models.TextField(blank=True, verbose_name="observações")),
                (
                    "origem_cadastro",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("inbox", "Inbox"),
                            ("importacao", "Importação"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="origem do cadastro",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                ("anonimizado", models.BooleanField(default=False, verbose_name="anonimizado")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pessoas_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="pessoas", to="pessoas.tag"),
                ),
            ],
            options={
                "verbose_name": "pessoa",
                "verbose_name_plural": "pessoas",
                "ordering": ["nome", "sobrenome"],
                "permissions": [
                    ("pode_desativar_pessoa", "Pode desativar pessoa (soft delete)"),
                    ("pode_reativar_pessoa", "Pode reativar pessoa desativada"),
                    ("pode_anonimizar_pessoa", "Pode anonimizar pessoa (LGPD)"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Entidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="nome")),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="nome fantasia"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("associacao_de_moradores", "Associação de moradores"),
                            ("sindicato", "Sindicato"),
                            ("partido", "Partido"),
                            ("escola", "Escola"),
                            ("conselho", "Conselho"),
                            ("igreja", "Igreja"),
                            ("ong", "ONG"),
                            ("empresa", "Empresa"),
                            ("orgao_publico", "Órgão público"),
                            ("coletivo", "Coletivo"),
                            ("familia", "Família"),
                            ("grupo_informal", "Grupo informal"),
                            ("condominio", "Condomínio"),
                            ("outros", "Outros"),
                        ],
                        max_length=30,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(blank=True, default="", max_length=18, verbose_name="CNPJ"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="telefone"
                    ),
                ),
                (
                    "site",
                    models.URLField(blank=True, default="", max_length=255, verbose_name="site"),
                ),
                ("cep", models.CharField(blank=True, default="", max_length=9, verbose_name="CEP")),
                (
                    "logradouro",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="logradouro"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, default="", max_length=20, verbose_name="número"),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="complemento"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="bairro"),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="cidade"),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, default="", max_length=2, verbose_name="estado (UF)"
                    ),
                ),
                ("observacoes", models.TextField(blank=True, verbose_name="observações")),
                ("ativo", models.BooleanField(default=True, verbose_name="ativa")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criada em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizada em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entidades_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="entidades", to="pessoas.tag"),
                ),
            ],
            options={
                "verbose_name": "entidade",
                "verbose_name_plural": "entidades",
                "ordering": ["nome"],
                "permissions": [
                    ("pode_desativar_entidade", "Pode desativar entidade (soft delete)"),
                    ("pode_reativar_entidade", "Pode reativar entidade desativada"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Vinculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("papel", models.CharField(max_length=100, verbose_name="papel")),
                ("data_inicio", models.DateField(blank=True, null=True, verbose_name="início")),
                ("data_fim", models.DateField(blank=True, null=True, verbose_name="fim")),
                ("observacao", models.TextField(blank=True, verbose_name="observação")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos",
                        to="pessoas.entidade",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos",
                        to="pessoas.pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo",
                "verbose_name_plural": "vínculos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="pessoa",
            name="entidades",
            field=models.ManyToManyField(
                blank=True, related_name="pessoas", through="pessoas.Vinculo", to="pessoas.entidade"
            ),
        ),
        migrations.AddIndex(
            model_name="entidade",
            index=models.Index(fields=["nome"], name="pessoas_ent_nome_d58238_idx"),
        ),
        migrations.AddIndex(
            model_name="entidade",
            index=models.Index(fields=["tipo"], name="pessoas_ent_tipo_66dad0_idx"),
        ),
        migrations.AddIndex(
            model_name="entidade",
            index=models.Index(fields=["ativo"], name="pessoas_ent_ativo_fd5db6_idx"),
        ),
        migrations.AddConstraint(
            model_name="entidade",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cnpj", ""), _negated=True),
                fields=("cnpj",),
                name="entidade_cnpj_unico_quando_preenchido",
            ),
        ),
        migrations.AddIndex(
            model_name="vinculo",
            index=models.Index(fields=["pessoa"], name="pessoas_vin_pessoa__5d4d2a_idx"),
        ),
        migrations.AddIndex(
            model_name="vinculo",
            index=models.Index(fields=["entidade"], name="pessoas_vin_entidad_57f197_idx"),
        ),
        migrations.AddIndex(
            model_name="pessoa",
            index=models.Index(fields=["nome", "sobrenome"], name="pessoas_pes_nome_4e071a_idx"),
        ),
        migrations.AddIndex(
            model_name="pessoa",
            index=models.Index(fields=["bairro"], name="pessoas_pes_bairro_966ee6_idx"),
        ),
        migrations.AddIndex(
            model_name="pessoa",
            index=models.Index(fields=["ativo"], name="pessoas_pes_ativo_a717a9_idx"),
        ),
        migrations.AddIndex(
            model_name="pessoa",
            index=models.Index(fields=["email"], name="pessoas_pes_email_66350b_idx"),
        ),
        migrations.AddIndex(
            model_name="pessoa",
            index=models.Index(fields=["telefone"], name="pessoas_pes_telefon_130668_idx"),
        ),
        migrations.AddIndex(
            model_name="pessoa",
            index=models.Index(fields=["whatsapp"], name="pessoas_pes_whatsap_379ed3_idx"),
        ),
        migrations.AddConstraint(
            model_name="pessoa",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cpf", ""), _negated=True),
                fields=("cpf",),
                name="pessoa_cpf_unico_quando_preenchido",
            ),
        ),
    ]
