# Generated by Django 5.2.14 on 2026-05-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pessoas", "0002_grupos_padrao"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="emailpessoa",
            constraint=models.UniqueConstraint(
                fields=("pessoa", "endereco"),
                name="email_unico_por_pessoa",
                violation_error_message="Esta pessoa já tem este e-mail cadastrado.",
            ),
        ),
        migrations.AddConstraint(
            model_name="redesocial",
            constraint=models.UniqueConstraint(
                fields=("pessoa", "plataforma", "valor"),
                name="rede_social_unica_por_pessoa",
                violation_error_message="Esta pessoa já tem este perfil cadastrado nesta plataforma.",
            ),
        ),
        migrations.AddConstraint(
            model_name="telefone",
            constraint=models.UniqueConstraint(
                fields=("pessoa", "numero"),
                name="telefone_unico_por_pessoa",
                violation_error_message="Esta pessoa já tem este número cadastrado.",
            ),
        ),
    ]
