# Generated by Django 5.2.14 on 2026-05-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={"verbose_name": "usuário", "verbose_name_plural": "usuários"},
        ),
        migrations.AddField(
            model_name="usuario",
            name="cargo",
            field=models.CharField(blank=True, max_length=100, verbose_name="cargo"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="nome_completo",
            field=models.CharField(blank=True, max_length=200, verbose_name="nome completo"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="e-mail"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
