# Generated by Django 5.2.14 on 2026-05-10 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_expand_usuario"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuario",
            managers=[],
        ),
    ]
