# Generated by Django 5.2.14 on 2026-05-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_usuario_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="coordenacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gabinete", "Gabinete"),
                    ("juridico", "Jurídico"),
                    ("comunicacao", "Comunicação"),
                ],
                default="",
                help_text="Define escopo de visibilidade de demandas (ADR 0041).",
                max_length=15,
                verbose_name="coordenação",
            ),
        ),
    ]
