# Generated by Django 5.2.14 on 2026-06-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_adicionar_coordenacao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "permissions": [("gerenciar_usuarios", "Pode gerenciar usuários da equipe")],
                "verbose_name": "usuário",
                "verbose_name_plural": "usuários",
            },
        ),
    ]
