# Generated by Django 5.2.14 on 2026-06-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_gerenciar_usuarios_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="coordenacao",
        ),
    ]
