# Generated by Django 5.2.14 on 2026-05-10 04:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pessoas", "0003_unicidade_canais"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Demanda",
            fields=[
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=20, unique=True, verbose_name="número"),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="título")),
                ("descricao", models.TextField(verbose_name="descrição")),
                (
                    "origem",
                    models.CharField(
                        choices=[("responsiva", "Responsiva"), ("proativa", "Proativa")],
                        default="responsiva",
                        max_length=15,
                    ),
                ),
                (
                    "canal_entrada",
                    models.CharField(
                        choices=[
                            ("dm_instagram", "DM Instagram"),
                            ("whatsapp", "WhatsApp"),
                            ("presencial", "Presencial"),
                            ("telefone", "Telefone"),
                            ("email", "E-mail"),
                            ("oficio", "Ofício"),
                            ("indicacao_interna", "Indicação interna"),
                            ("redes_sociais", "Redes sociais"),
                            ("outro", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="canal de entrada",
                    ),
                ),
                ("anonimo", models.BooleanField(default=False, verbose_name="anônima")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("novo", "Novo"),
                            ("em_andamento", "Em andamento"),
                            ("aguardando_terceiros", "Aguardando terceiros"),
                            ("aguardando_pessoa", "Aguardando pessoa"),
                            ("respondido", "Respondido"),
                            ("arquivado", "Arquivado"),
                        ],
                        default="novo",
                        max_length=25,
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("atendido", "Atendido"),
                            ("atendido_parcialmente", "Atendido parcialmente"),
                            ("nao_atendido", "Não atendido"),
                            ("inviavel", "Inviável"),
                            ("nao_se_aplica", "Não se aplica"),
                        ],
                        default="pendente",
                        max_length=25,
                    ),
                ),
                (
                    "resultado_observacao",
                    models.TextField(
                        blank=True, default="", verbose_name="observação do resultado"
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "coordenacao_responsavel",
                    models.CharField(
                        choices=[
                            ("gabinete", "Gabinete"),
                            ("juridico", "Jurídico"),
                            ("comunicacao", "Comunicação"),
                        ],
                        max_length=15,
                        verbose_name="coordenação responsável",
                    ),
                ),
                ("restrito", models.BooleanField(default=False, verbose_name="restrita")),
                ("prazo", models.DateField(blank=True, null=True)),
                (
                    "retorno_data",
                    models.DateField(blank=True, null=True, verbose_name="data do retorno"),
                ),
                (
                    "retorno_conteudo",
                    models.TextField(blank=True, default="", verbose_name="conteúdo do retorno"),
                ),
                (
                    "retorno_canal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dm_instagram", "DM Instagram"),
                            ("whatsapp", "WhatsApp"),
                            ("presencial", "Presencial"),
                            ("telefone", "Telefone"),
                            ("email", "E-mail"),
                            ("oficio", "Ofício"),
                            ("indicacao_interna", "Indicação interna"),
                            ("redes_sociais", "Redes sociais"),
                            ("outro", "Outro"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="canal do retorno",
                    ),
                ),
                (
                    "observacoes_arquivamento",
                    models.TextField(
                        blank=True, default="", verbose_name="observações de arquivamento"
                    ),
                ),
                (
                    "arquivado_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="arquivada em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandas_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandas_responsavel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="demandas", to="pessoas.tag"),
                ),
            ],
            options={
                "verbose_name": "demanda",
                "verbose_name_plural": "demandas",
                "ordering": ["-criado_em"],
                "permissions": [
                    ("pode_arquivar_demanda", "Pode arquivar demanda respondida"),
                    (
                        "pode_arquivar_sem_responder",
                        "Pode arquivar demanda não respondida (com justificativa)",
                    ),
                    ("pode_marcar_restrita", "Pode marcar/desmarcar demanda como restrita"),
                    ("pode_atribuir_responsavel", "Pode atribuir/reatribuir responsável"),
                    ("pode_reabrir_demanda", "Pode reabrir demanda respondida"),
                    ("pode_excluir_demanda", "Pode excluir demanda definitivamente"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DemandaEntidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("papel", models.CharField(blank=True, default="", max_length=100)),
                ("observacao", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "demanda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demanda_entidades",
                        to="demandas.demanda",
                    ),
                ),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demanda_entidades",
                        to="pessoas.entidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "parte (entidade)",
                "verbose_name_plural": "partes (entidades)",
            },
        ),
        migrations.AddField(
            model_name="demanda",
            name="entidades",
            field=models.ManyToManyField(
                related_name="demandas", through="demandas.DemandaEntidade", to="pessoas.entidade"
            ),
        ),
        migrations.CreateModel(
            name="DemandaPessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("papel", models.CharField(blank=True, default="", max_length=100)),
                ("observacao", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "demanda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demanda_pessoas",
                        to="demandas.demanda",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demanda_pessoas",
                        to="pessoas.pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "parte (pessoa)",
                "verbose_name_plural": "partes (pessoas)",
            },
        ),
        migrations.AddField(
            model_name="demanda",
            name="pessoas",
            field=models.ManyToManyField(
                related_name="demandas", through="demandas.DemandaPessoa", to="pessoas.pessoa"
            ),
        ),
        migrations.CreateModel(
            name="Encaminhamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "destinatario_orgao",
                    models.CharField(max_length=200, verbose_name="órgão destinatário"),
                ),
                (
                    "destinatario_pessoa",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="pessoa destinatária"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("oficio", "Ofício"),
                            ("requerimento_informacao", "Requerimento de informação"),
                            ("indicacao", "Indicação"),
                            ("ligacao", "Ligação"),
                            ("email", "E-mail"),
                            ("presencial", "Presencial"),
                            ("outro", "Outro"),
                        ],
                        max_length=40,
                    ),
                ),
                ("numero_documento", models.CharField(blank=True, default="", max_length=50)),
                ("data_envio", models.DateField()),
                ("prazo_resposta", models.DateField(blank=True, null=True)),
                ("data_resposta", models.DateField(blank=True, null=True)),
                ("conteudo_resposta", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enviado", "Enviado"),
                            ("prazo_vencido", "Prazo vencido"),
                            ("respondido_satisfatorio", "Respondido (satisfatório)"),
                            ("respondido_insatisfatorio", "Respondido (insatisfatório)"),
                            ("sem_resposta", "Sem resposta"),
                        ],
                        default="enviado",
                        max_length=30,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encaminhamentos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "demanda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encaminhamentos",
                        to="demandas.demanda",
                    ),
                ),
            ],
            options={
                "verbose_name": "encaminhamento",
                "verbose_name_plural": "encaminhamentos",
                "ordering": ["-data_envio"],
                "permissions": [("pode_excluir_encaminhamento", "Pode excluir encaminhamento")],
            },
        ),
        migrations.CreateModel(
            name="Interacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("registro_inicial", "Registro inicial"),
                            ("contato_com_pessoa", "Contato com pessoa"),
                            ("contato_interno", "Contato interno"),
                            ("reuniao", "Reunião"),
                            ("encaminhamento_externo", "Encaminhamento externo"),
                            ("retorno_externo_recebido", "Retorno externo recebido"),
                            ("mudanca_status", "Mudança de status"),
                            ("mudanca_responsavel", "Mudança de responsável"),
                            ("mudanca_resultado", "Mudança de resultado"),
                            ("arquivamento", "Arquivamento"),
                            ("anotacao_interna", "Anotação interna"),
                        ],
                        max_length=40,
                    ),
                ),
                ("conteudo", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("realizada", "Realizada"),
                            ("agendada", "Agendada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="realizada",
                        max_length=15,
                    ),
                ),
                ("data_ocorrencia", models.DateTimeField()),
                ("automatica", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "demanda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interacoes",
                        to="demandas.demanda",
                    ),
                ),
                (
                    "interacao_origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_ups",
                        to="demandas.interacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "interação",
                "verbose_name_plural": "interações",
                "ordering": ["-data_ocorrencia"],
                "permissions": [
                    ("pode_editar_interacao_alheia", "Pode editar interação de outro autor")
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemInbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("conteudo", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("processado", "Processado"),
                            ("descartado", "Descartado"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("motivo_descarte", models.TextField(blank=True, default="")),
                ("processado_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_inbox",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "demanda_gerada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itens_inbox",
                        to="demandas.demanda",
                    ),
                ),
                (
                    "processado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itens_processados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "item de inbox",
                "verbose_name_plural": "itens de inbox",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Anexo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("arquivo", models.FileField(upload_to="anexos/%Y/%m/")),
                ("nome_original", models.CharField(max_length=255)),
                ("tamanho_bytes", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, default="")),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anexos_enviados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "anexo",
                "verbose_name_plural": "anexos",
                "ordering": ["-enviado_em"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="demandas_an_content_cc1c8f_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="demandaentidade",
            index=models.Index(fields=["demanda"], name="demandas_de_demanda_d999a9_idx"),
        ),
        migrations.AddIndex(
            model_name="demandaentidade",
            index=models.Index(fields=["entidade"], name="demandas_de_entidad_a1747b_idx"),
        ),
        migrations.AddConstraint(
            model_name="demandaentidade",
            constraint=models.UniqueConstraint(
                fields=("demanda", "entidade"),
                name="demanda_entidade_unica",
                violation_error_message="Esta entidade já é parte desta demanda.",
            ),
        ),
        migrations.AddIndex(
            model_name="demandapessoa",
            index=models.Index(fields=["demanda"], name="demandas_de_demanda_1fa528_idx"),
        ),
        migrations.AddIndex(
            model_name="demandapessoa",
            index=models.Index(fields=["pessoa"], name="demandas_de_pessoa__e10a43_idx"),
        ),
        migrations.AddConstraint(
            model_name="demandapessoa",
            constraint=models.UniqueConstraint(
                fields=("demanda", "pessoa"),
                name="demanda_pessoa_unica",
                violation_error_message="Esta pessoa já é parte desta demanda.",
            ),
        ),
        migrations.AddIndex(
            model_name="demanda",
            index=models.Index(fields=["responsavel"], name="demandas_de_respons_362fd8_idx"),
        ),
        migrations.AddIndex(
            model_name="demanda",
            index=models.Index(fields=["status"], name="demandas_de_status_25dba6_idx"),
        ),
        migrations.AddIndex(
            model_name="demanda",
            index=models.Index(fields=["resultado"], name="demandas_de_resulta_5d9569_idx"),
        ),
        migrations.AddIndex(
            model_name="demanda",
            index=models.Index(
                fields=["status", "coordenacao_responsavel"], name="demandas_de_status_4048ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="demanda",
            index=models.Index(
                fields=["responsavel", "status"], name="demandas_de_respons_156971_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="demanda",
            index=models.Index(
                fields=["resultado", "criado_em"], name="demandas_de_resulta_cf2957_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="demanda",
            index=models.Index(fields=["criado_em"], name="demandas_de_criado__86892d_idx"),
        ),
        migrations.AddIndex(
            model_name="demanda",
            index=models.Index(fields=["prazo"], name="demandas_de_prazo_6641b1_idx"),
        ),
        migrations.AddIndex(
            model_name="encaminhamento",
            index=models.Index(fields=["demanda"], name="demandas_en_demanda_b80b40_idx"),
        ),
        migrations.AddIndex(
            model_name="encaminhamento",
            index=models.Index(
                fields=["destinatario_orgao"], name="demandas_en_destina_583ba9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="encaminhamento",
            index=models.Index(
                fields=["prazo_resposta", "status"], name="demandas_en_prazo_r_2d2293_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interacao",
            index=models.Index(fields=["demanda"], name="demandas_in_demanda_6bd777_idx"),
        ),
        migrations.AddIndex(
            model_name="interacao",
            index=models.Index(
                fields=["demanda", "-data_ocorrencia"], name="demandas_in_demanda_4523f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interacao",
            index=models.Index(
                fields=["autor", "status", "data_ocorrencia"], name="demandas_in_autor_i_d86963_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interacao",
            index=models.Index(
                fields=["status", "data_ocorrencia"], name="demandas_in_status_f40c1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="iteminbox",
            index=models.Index(
                fields=["status", "criado_em"], name="demandas_it_status_b93d9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="iteminbox",
            index=models.Index(fields=["autor"], name="demandas_it_autor_i_faf152_idx"),
        ),
    ]
