# Generated by Django 5.2.14 on 2026-05-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demandas", "0002_grupos_padrao_demandas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demanda",
            name="tags",
        ),
        migrations.CreateModel(
            name="Tema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True, verbose_name="nome")),
                (
                    "cor",
                    models.CharField(
                        blank=True, help_text="Hex #RRGGBB", max_length=7, verbose_name="cor"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
            ],
            options={
                "verbose_name": "tema",
                "verbose_name_plural": "temas",
                "ordering": ["nome"],
                "indexes": [models.Index(fields=["ativo"], name="demandas_te_ativo_a17837_idx")],
            },
        ),
        migrations.AddField(
            model_name="demanda",
            name="temas",
            field=models.ManyToManyField(blank=True, related_name="demandas", to="demandas.tema"),
        ),
    ]
