# Generated by Django 5.2.14 on 2026-05-16 15:47
# Refeita à mão para incluir a data migration descrita na ADR 0043.

from datetime import datetime, time

from django.db import migrations, models
from django.utils import timezone


def _migrar_retornos_para_interacoes(apps, schema_editor):
    """Para cada demanda com status='respondido' E retorno_data preenchido,
    cria uma Interacao(tipo=devolutiva). Em seguida, troca o status
    'respondido' para 'concluida'. Ver ADR 0043."""
    Demanda = apps.get_model("demandas", "Demanda")
    Interacao = apps.get_model("demandas", "Interacao")
    canal_choices = dict(
        [
            ("dm_instagram", "DM Instagram"),
            ("whatsapp", "WhatsApp"),
            ("presencial", "Presencial"),
            ("telefone", "Telefone"),
            ("email", "E-mail"),
            ("oficio", "Ofício"),
            ("indicacao_interna", "Indicação interna"),
            ("redes_sociais", "Redes sociais"),
            ("outro", "Outro"),
        ]
    )
    for demanda in Demanda.objects.filter(retorno_data__isnull=False):
        canal_label = canal_choices.get(demanda.retorno_canal or "", demanda.retorno_canal or "")
        cabecalho = f"Canal: {canal_label}\n\n" if canal_label else ""
        Interacao.objects.create(
            demanda=demanda,
            autor=demanda.criado_por,
            tipo="devolutiva",
            conteudo=f"{cabecalho}{demanda.retorno_conteudo or ''}".strip(),
            status="realizada",
            data_ocorrencia=timezone.make_aware(
                datetime.combine(demanda.retorno_data, time(12, 0))
            ),
            automatica=False,
        )
    Demanda.objects.filter(status="respondido").update(status="concluida")


def _reverter(apps, schema_editor):
    """Reverte status; devolutivas criadas não são removidas (idempotência segura)."""
    Demanda = apps.get_model("demandas", "Demanda")
    Demanda.objects.filter(status="concluida").update(status="respondido")


class Migration(migrations.Migration):

    dependencies = [
        ("demandas", "0004_grupos_padrao_tema"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="demanda",
            options={
                "ordering": ["-criado_em"],
                "permissions": [
                    ("pode_arquivar_demanda", "Pode arquivar demanda concluída"),
                    (
                        "pode_arquivar_sem_responder",
                        "Pode arquivar demanda não concluída (com justificativa)",
                    ),
                    ("pode_marcar_restrita", "Pode marcar/desmarcar demanda como restrita"),
                    ("pode_atribuir_responsavel", "Pode atribuir/reatribuir responsável"),
                    ("pode_reabrir_demanda", "Pode reabrir demanda concluída"),
                    ("pode_excluir_demanda", "Pode excluir demanda definitivamente"),
                ],
                "verbose_name": "demanda",
                "verbose_name_plural": "demandas",
            },
        ),
        migrations.AlterField(
            model_name="interacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("registro_inicial", "Registro inicial"),
                    ("contato_com_pessoa", "Contato com pessoa"),
                    ("contato_interno", "Contato interno"),
                    ("reuniao", "Reunião"),
                    ("encaminhamento_externo", "Encaminhamento externo"),
                    ("retorno_externo_recebido", "Retorno externo recebido"),
                    ("devolutiva", "Devolutiva ao demandante"),
                    ("mudanca_status", "Mudança de status"),
                    ("mudanca_responsavel", "Mudança de responsável"),
                    ("mudanca_resultado", "Mudança de resultado"),
                    ("arquivamento", "Arquivamento"),
                    ("anotacao_interna", "Anotação interna"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="demanda",
            name="status",
            field=models.CharField(
                choices=[
                    ("novo", "Novo"),
                    ("em_andamento", "Em andamento"),
                    ("aguardando_terceiros", "Aguardando terceiros"),
                    ("aguardando_pessoa", "Aguardando pessoa"),
                    ("concluida", "Concluída"),
                    ("arquivado", "Arquivado"),
                ],
                default="novo",
                max_length=25,
            ),
        ),
        migrations.RunPython(_migrar_retornos_para_interacoes, _reverter),
        migrations.RemoveField(
            model_name="demanda",
            name="retorno_canal",
        ),
        migrations.RemoveField(
            model_name="demanda",
            name="retorno_conteudo",
        ),
        migrations.RemoveField(
            model_name="demanda",
            name="retorno_data",
        ),
    ]
