# Generated by Django 5.2.14 on 2026-05-16 16:50
# Refeita à mão para incluir data migration descrita na ADR 0045.

import django.db.models.deletion
from django.db import migrations, models


def _ligar_interacoes_a_encaminhamentos(apps, schema_editor):
    """Best-effort: para cada Interacao histórica de tipo
    'encaminhamento_externo' ou 'retorno_externo_recebido', tenta achar
    o Encaminhamento correspondente na mesma demanda. Se houver apenas um,
    liga. Se houver vários, deixa NULL (não corrompe dados — o expand
    simplesmente não aparece). Ver ADR 0045."""
    Interacao = apps.get_model("demandas", "Interacao")
    Encaminhamento = apps.get_model("demandas", "Encaminhamento")
    relevantes = Interacao.objects.filter(
        tipo__in=("encaminhamento_externo", "retorno_externo_recebido")
    )
    for interacao in relevantes:
        candidatos = Encaminhamento.objects.filter(demanda_id=interacao.demanda_id)
        if candidatos.count() == 1:
            interacao.encaminhamento_id = candidatos.first().pk
            interacao.save(update_fields=["encaminhamento"])


def _reverter(apps, schema_editor):
    """Reverter limpa a FK; o campo será removido junto com a migração."""
    Interacao = apps.get_model("demandas", "Interacao")
    Interacao.objects.update(encaminhamento=None)


class Migration(migrations.Migration):

    dependencies = [
        ("demandas", "0005_devolutiva_como_interacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="interacao",
            name="encaminhamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interacoes",
                to="demandas.encaminhamento",
            ),
        ),
        migrations.RunPython(_ligar_interacoes_a_encaminhamentos, _reverter),
    ]
