# Generated by Django 5.2.14 on 2026-05-17 03:59
# Refeita à mão para incluir data migration: converte papel free-text em
# choice quando possível; senão papel='outro' + papel_outro = texto original.

from django.db import migrations, models


PAPEL_PESSOA_CHOICES = {"solicitante", "afetada", "testemunha", "representante", "outro"}
PAPEL_ENTIDADE_CHOICES = {"representada", "afetada", "parceira", "outro"}


def _normalizar_papel(apps, schema_editor):
    """Para cada linha existente, se o papel atual não bate com a nova lista
    de choices, move o texto pra papel_outro e seta papel='outro'.
    Texto vazio vira default (solicitante / representada — vão pelo
    DEFAULT do field, não pelo update aqui)."""
    DemandaPessoa = apps.get_model("demandas", "DemandaPessoa")
    DemandaEntidade = apps.get_model("demandas", "DemandaEntidade")

    for dp in DemandaPessoa.objects.all():
        valor = (dp.papel or "").strip().lower()
        if valor and valor not in PAPEL_PESSOA_CHOICES:
            dp.papel_outro = dp.papel
            dp.papel = "outro"
            dp.save(update_fields=["papel", "papel_outro"])

    for de in DemandaEntidade.objects.all():
        valor = (de.papel or "").strip().lower()
        if valor and valor not in PAPEL_ENTIDADE_CHOICES:
            de.papel_outro = de.papel
            de.papel = "outro"
            de.save(update_fields=["papel", "papel_outro"])


def _reverter(apps, schema_editor):
    """Reverte: papel='outro' com texto em papel_outro volta a ser texto livre
    no campo papel."""
    DemandaPessoa = apps.get_model("demandas", "DemandaPessoa")
    DemandaEntidade = apps.get_model("demandas", "DemandaEntidade")
    for dp in DemandaPessoa.objects.filter(papel="outro").exclude(papel_outro=""):
        dp.papel = dp.papel_outro
        dp.papel_outro = ""
        dp.save(update_fields=["papel", "papel_outro"])
    for de in DemandaEntidade.objects.filter(papel="outro").exclude(papel_outro=""):
        de.papel = de.papel_outro
        de.papel_outro = ""
        de.save(update_fields=["papel", "papel_outro"])


class Migration(migrations.Migration):

    dependencies = [
        ("demandas", "0006_interacao_encaminhamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demandaentidade",
            name="observacao",
        ),
        migrations.RemoveField(
            model_name="demandapessoa",
            name="observacao",
        ),
        migrations.AddField(
            model_name="demandaentidade",
            name="papel_outro",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Preencha apenas se papel = 'Outro'.",
                max_length=100,
                verbose_name="papel (outro)",
            ),
        ),
        migrations.AddField(
            model_name="demandapessoa",
            name="papel_outro",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Preencha apenas se papel = 'Outro'.",
                max_length=100,
                verbose_name="papel (outro)",
            ),
        ),
        # Data migration ANTES do AlterField pra que o papel ainda aceite
        # qualquer string ao ler dados antigos.
        migrations.RunPython(_normalizar_papel, _reverter),
        migrations.AlterField(
            model_name="demandaentidade",
            name="papel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("representada", "Representada"),
                    ("afetada", "Afetada"),
                    ("parceira", "Parceira"),
                    ("outro", "Outro"),
                ],
                default="representada",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="demandapessoa",
            name="papel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("solicitante", "Solicitante"),
                    ("afetada", "Afetada"),
                    ("testemunha", "Testemunha"),
                    ("representante", "Representante"),
                    ("outro", "Outro"),
                ],
                default="solicitante",
                max_length=20,
            ),
        ),
    ]
