# Generated by Django 5.2.14 on 2026-06-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demandas", "0008_renumerar_demandas_formato_d_aamm_nnnnn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demandaentidade",
            name="papel",
        ),
        migrations.RemoveField(
            model_name="demandaentidade",
            name="papel_outro",
        ),
        migrations.RemoveField(
            model_name="demandapessoa",
            name="papel",
        ),
        migrations.RemoveField(
            model_name="demandapessoa",
            name="papel_outro",
        ),
    ]
