# Generated by Django 5.2.14 on 2026-06-22 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demandas", "0010_demanda_slug_publico"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="demanda",
            options={
                "ordering": ["-criado_em"],
                "permissions": [
                    ("pode_arquivar_demanda", "Pode arquivar demanda concluída"),
                    (
                        "pode_arquivar_sem_responder",
                        "Pode arquivar demanda não concluída (com justificativa)",
                    ),
                    ("pode_atribuir_responsavel", "Pode atribuir/reatribuir responsável"),
                    ("pode_reabrir_demanda", "Pode reabrir demanda concluída"),
                    ("pode_excluir_demanda", "Pode excluir demanda definitivamente"),
                ],
                "verbose_name": "demanda",
                "verbose_name_plural": "demandas",
            },
        ),
        migrations.RemoveField(
            model_name="demanda",
            name="restrito",
        ),
    ]
