# Generated by Django 5.2.14 on 2026-06-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demandas", "0011_drop_restrito"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="demanda",
            name="demandas_de_status_4048ff_idx",
        ),
        migrations.RemoveField(
            model_name="demanda",
            name="coordenacao_responsavel",
        ),
    ]
